language: go

go:
  - 1.11.x

services:
  - postgresql

env:
  - DB_ADDR=postgresql://postgres@localhost:5432/travis_ci_test?sslmode=disable CODECOV_TOKEN="e2c72939-f5b1-4ff4-ac4b-72ece616a5be"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

before_install:
  - go get github.com/tools/godep
  - go get -u github.com/go-swagger/go-swagger/cmd/swagger

install:
  - godep restore
  - swagger generate client --target=rest -f tools/swagger.yml
  - swagger generate server --target=rest -f tools/swagger.yml

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)